In [43]:
import numpy as np # use for scienctify calculationn
import pandas as pd 


In [11]:
dataset=pd.read_csv('data.csv')


In [13]:
dataset

,Country,Age,Salary,Purchased
0,France,44.0,72000.0,No
1,Spain,27.0,48000.0,Yes
2,Germany,30.0,54000.0,No
3,Spain,38.0,61000.0,No
4,Germany,40.0,NaN,Yes
5,France,35.0,58000.0,Yes
6,Spain,NaN,52000.0,No
7,France,48.0,79000.0,Yes
8,Germany,50.0,83000.0,No
9,France,37.0,67000.0,Yes


In [19]:
x=dataset[['Country','Age','Salary']].values



In [21]:
x


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [27]:
y=dataset[['Purchased']].values


In [29]:
y


array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [31]:
# filtering the data it means replacing or remvoing or  removing unwante data
from sklearn.impute import SimpleImputer

In [47]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') # shift tab all parm are show take missing value

In [49]:
imputer=imputer.fit(x[:,1:3])


In [53]:
x[:,1:3]=imputer.transform(x[:,1:3]) # replace nan with mean 

In [55]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [57]:
# convert catogorical data convert into numeric data
from sklearn.preprocessing import LabelEncoder

In [59]:
label_encoder_x=LabelEncoder()

In [63]:
x[:,0]=label_encoder_x.fit_transform(x[:,0])

In [65]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [69]:
# now do dummy  encodinng in country which contain only 0,1 in which 1 contain same name like if germany - germany , 0 like spian - grmany
from sklearn.preprocessing import OneHotEncoder

In [71]:
onehotencoder=OneHotEncoder()

In [75]:
x=onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

In [77]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [79]:
label_encoder_y=LabelEncoder()

In [81]:
y=label_encoder_y.fit_transform(y)

C:\Anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [83]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [87]:
#split the dataset because some of the dataset use for train the ml model and some is use to check the prediction of the output
from sklearn.model_selection import train_test_split

In [138]:
x_test,x_train,y_test,y_train=train_test_split(x,y,train_size=0.2,random_state=0) # train_size=0 shows that 20% dataset use for testing and remainging use for traing(80) the model and 
#random_size=0 show that ever iternation the output is same

In [140]:
x_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [142]:
x_test

array([[1., 0., 0.],
       [1., 0., 0.]])

In [103]:
y_train

array([0, 0, 1, 1, 1, 0, 1, 0])

In [105]:
y_test

array([0, 1])

In [107]:
#feature scalling if in a dataset feature are varing in large scale so we data have to be in same scale
from sklearn.preprocessing import StandardScaler

In [109]:
sc_x=StandardScaler()

In [111]:
x_train=sc_x.fit_transform(x_train)

In [132]:
x_test=sc_x.fit_transform(x_test)

In [134]:
x_train

array([[-0.57735027,  1.29099445, -0.77459667],
       [-0.57735027,  1.29099445, -0.77459667],
       [-0.57735027,  1.29099445, -0.77459667],
       [ 1.73205081, -0.77459667, -0.77459667],
       [-0.57735027, -0.77459667,  1.29099445],
       [-0.57735027, -0.77459667,  1.29099445],
       [ 1.73205081, -0.77459667, -0.77459667],
       [-0.57735027, -0.77459667,  1.29099445]])

In [136]:
x_test

array([[0., 0., 0.],
       [0., 0., 0.]])